package uc3m.crypto.server.model;

import uc3m.crypto.security.RSA;
import uc3m.crypto.security.SHA;

import javax.crypto.SecretKey;
import java.io.Serializable;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.SignatureException;
import java.text.SimpleDateFormat;
import java.util.Base64;
import java.util.Date;

public class Message implements Serializable {
    private String sender;
    private String content;
    private Date dateSent;
    private String hmac;
    private String sig;

    public Message(String sender, String content, Date dateSent) {
        this.sender = sender;
        this.content = content;
        this.dateSent = dateSent;
        this.hmac = "";
        this.sig = "";
    }

    public Message(String message) { //Message from string, the same as generated by toString()
        sender = message.substring(message.indexOf("sender") + 8,
                message.indexOf("'", message.indexOf("sender") + 8));
        content = message.substring(message.indexOf("content") + 9,
                message.indexOf("'", message.indexOf("content") + 9));
        String date = message.substring(message.indexOf("dateSent") + 10,
                message.indexOf("'", message.indexOf("dateSent") + 10));
        SimpleDateFormat dateFormatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        try {
            dateSent = dateFormatter.parse(date);
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        hmac = message.substring(message.indexOf("hmac") + 6,
                message.indexOf("'", message.indexOf("hmac") + 6));
        sig = message.substring(message.indexOf("sig") + 5,
                message.indexOf("'", message.indexOf("sig") + 5));
    }

    public Message(String message, SecretKey key) {
        this(message);
        this.checkHmac(key);
    }

    @Override
    public String toString() {
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        return "Message{" +
                "sender='" + sender + '\'' +
                ", content='" + content + '\'' +
                ", dateSent='" + formatter.format(dateSent) + '\'' +
                ", hmac='" + hmac + '\'' +
                ", sig='" + sig + '\'' +
                '}';
    }

    public String toStringWithoutHmac() { //to string without HMAC for HMAC generation
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        return "Message{" +
                "sender='" + sender + '\'' +
                ", content='" + content + '\'' +
                ", dateSent='" + formatter.format(dateSent) + '\'' +
                '}';
    }

    public String toUIString() { //this string is printed on the user interface
        SimpleDateFormat formatter = new SimpleDateFormat("HH:mm:ss");
        return "(" + formatter.format(dateSent) + ")[" + sender + "]: " + content;
    }

    public String getHmacString(SecretKey key) { //get HMAC value of the message as Base64 string
        return Base64.getEncoder().encodeToString(SHA.digest(this.toStringWithoutHmac()
                + Base64.getEncoder().encodeToString(key.getEncoded())));
    }
    public boolean checkHmac(SecretKey key) { //check if the newly generated HMAC equals to the saved one, integrity check
        if (getHmacString(key).equals(hmac)) {
            return true;
        }
        else {
            throw new SecurityException("Message integrity compromised");
        }
    }

    public String getHash() {
        return Base64.getEncoder().encodeToString(SHA.digest(this.toStringWithoutHmac()));
    }

    public void sign(PrivateKey key) {
        setSig(RSA.sign(toStringWithoutHmac(), key));
    }
    public boolean verifySignature(PublicKey key) {
        return RSA.verifySignature(toStringWithoutHmac(), key, getSig());
    }

    public String getSender() {
        return sender;
    }

    public void setSender(String sender) {
        this.sender = sender;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Date getDateSent() {
        return dateSent;
    }

    public void setDateSent(Date dateSent) {
        this.dateSent = dateSent;
    }

    public String getHmac() {
        return hmac;
    }

    public Message setHmac(SecretKey key) {
        this.hmac = getHmacString(key);
        return this;
    }

    public String getSig() {
        return sig;
    }

    public void setSig(String sig) {
        this.sig = sig;
    }
}
